### ISSUE TITLE
SVG todo list

### ISSUE THREAD

**Issue by putianyi889** [putianyi889/MS-Texture#9]
- [ ] Arbiter https://github.com/Minesweeper-World/MS-Texture/issues/11
- [ ] Winmine XP https://github.com/Minesweeper-World/MS-Texture/issues/12
- [ ] Winmine 98
- [ ] Winmine 7
- [ ] Minesweeper GO
- [ ] League of Minesweeper
